### ISSUE TITLE
Add info about compiling from Source

### ISSUE THREAD

**Issue by academik** [khronokernel/Opencore-Vanilla-Desktop-Guide#11]
First, thank you for such a thoughtful and thorough guide. I appreciate the way you've laid things out and given so many visual references throughout. 

I'd like to ask for a quick addendum to help non-programmers on building from scratch. 

You start the guide with:
<blockquote>
OpenCorePkg (Recommend to build from scratch instead of using the prebuilt package as OpenCore is constantly being updated. As of writing, we're on Version 0.5.3 even though the current official release is 0.5.2). The easiest way to build is via the macbuild.tool, you will need Xcode's Commandline tools
</blockquote>

I have Xcode and the Command Line tools. 
I don't know how to use the MacBuild tool... or how to build any of the source files into useful files (going from [this](https://github.com/Mieze/IntelMausiEthernet/) to IntelMausiEthernet.kext). 

I've Google-Fu'd my way through numerous tutorials, but even though I have lots of new files on my computer, I still don't have any files that look the ones for the EFI (or things that seem useful).

You've got a really clear way of explaining things, and I bet this process is straightforward. I'd love for there to be a section on how to compile things from source. 

Thanks!
Andrew

PS - DIdn't see another way to reach out to you

**Comment by dhinakg** [comment]
Double clicking on `macbuild.tool` or opening Terminal, `cd`ing to the directory, and `./macbuild.tool` works.
The products can be found in the `Binaries` folder.

Regarding adding it to the guide, that is up for khronokernel to decide if and how they will do it.

**Comment by khronokernel** [comment]
No longer recommending users to compile OpenCore themselves since development has slowed down so will not be including instructions on compiling yourself
