### ISSUE TITLE
the apple logo be out of shape

### ISSUE THREAD

**Issue by robotwai** [khronokernel/Opencore-Vanilla-Desktop-Guide#12]
the first logo is not same last

**Comment by robotwai** [comment]
when i hide the verbose

**Comment by khronokernel** [comment]
Did you follow this?: https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide/troubleshooting/verbose

**Comment by khronokernel** [comment]
This is also for issues with the guide, not with your hackintosh install. Please keep stuff like this on forums like r/hackintosh and the respective discord
