### ISSUE TITLE
Scan Policy wrong value allow usb

### ISSUE THREAD

**Issue by czombos** [khronokernel/Opencore-Vanilla-Desktop-Guide#15]
In security.md "And lets just say for this example that you want to add OC_SCAN_ALLOW_DEVICE_USB:"
`0x00400000` + `0xF0103` = `0x4F0103`
OC_SCAN_ALLOW_DEVICE_USB = `0x00200000`

`0x00200000` + `0xF0103` = `0x2F0103`
And converting this to decimal gives us `3080451`

**Comment by mipxx** [comment]
fixed in #18
