### ISSUE TITLE
Halting on "Plist only kext has CFBundleExecutable key"

### ISSUE THREAD

**Issue by impulse** [khronokernel/Opencore-Vanilla-Desktop-Guide#22]
Followed the guide however my boot halts because of USBInjectAll and VoodooPS2 kexts since they have that key present.

**Comment by khronokernel** [comment]
Is this an issue with the guide itself? If you're able to find an issue with the guide, I'm more than happy to correct it but the issues page is not for troubleshooting your install. Keep that for forums, subreddits and such please. I'll leave this thread closed for now but if you find issues with the guide I'm more than happy to correct.

**Comment by impulse** [comment]
Hi @khronokernel 

sorry for the confusion but the issue was indeed meant to be a problem with the guide. 

The guide states the following:
>A reminder that ProperTree users can run Cmd/Ctrl+R to add all their kexts in the correct order without manually typing each kext out.

So my expectation for running that command would be to not run into this error. I'd usually doubt my ability to read, however it's a fairly simple step (which I assume to not have done wrong) and would require additions to the guide.
