### ISSUE TITLE
Unfinished sentence

### ISSUE THREAD

**Issue by 78rr7r67r67** [khronokernel/Opencore-Vanilla-Desktop-Guide#23]
Commit 6ee5941af4d454b95263b5a0fa66d12fa3a015c9 introduced the following sentence in extras/troubleshooting.md (currently line 123):  

![grafik](https://user-images.githubusercontent.com/17459866/72461885-2fa09600-37d0-11ea-9584-e7effb219753.png)

There currently is no guide on how to troubleshoot broken audio.

**Comment by khronokernel** [comment]
Oh thank you for that, fixed in latest commit: [0af61bc](https://github.com/khronokernel/Opencore-Vanilla-Desktop-Guide/commit/0af61bc1db155c7bf6a955b0049f03a5055b8659)
