### ISSUE TITLE
Link referring to TSCAdjustReset,zip is broken, leads to 404

### ISSUE THREAD

**Issue by deadair3210** [khronokernel/Opencore-Vanilla-Desktop-Guide#25]
The link to the zip for TSCAdjustReset is broken, all it does is lead to a 404

**Comment by khronokernel** [comment]
O thanks for that! Fixed in latest commit: [a868160](https://github.com/khronokernel/Opencore-Vanilla-Desktop-Guide/commit/a8681605833d9369bace83afd2ba9026126d4908)
