### ISSUE TITLE
Dead links on gitbook

### ISSUE THREAD

**Issue by gillesdubois** [khronokernel/Opencore-Vanilla-Desktop-Guide#26]
Hi,

In the first place thx for your guide, it was really helpful. My Ryzentosh work like a charm :) 

However, while i was readinf your gitbook : https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide/
I noticed some deadlink.

Its not an exhaustive list but here is some broken link :
amd-config#post-install => Disable OpenCore Logging
general-troubleshooting => macOS booting issues

Regards,
Gilles Dubois.

**Comment by khronokernel** [comment]
Oh thank you for this! Had no idea they were broken, will go through and try to see how many are broken. Might take a bit for me to fix this though

**Comment by gillesdubois** [comment]
No problems, i will try to check your documentation as well to give you a more detailed list :)

**Comment by gillesdubois** [comment]
I checked the external link and few of them are invalid. I will give you an exhaustive list of the internal link :

- Opencore-Vanilla-Desktop-Guide/AMD/AMD-USB-map.md
✖ https://github.com/khronokernel/Opencore-Vanilla-Desktop-Guide/blob/master/extra-files/SSDT-USBX-AMD.aml:159:111

- Opencore-Vanilla-Desktop-Guide/misc/credit.md
✖ https://github.com/bpetru05:34:14
✖ https://kb.hackintoshisfun.ml/vanilla/:49:45

- Opencore-Vanilla-Desktop-Guide/post-install/spoof.md
✖ https://github.com/khronokernel/Opencore-Vanilla-Desktop-Guide/tree/d6ae62c258e16382e0746e9ffd1e9755c93b08d7/extras/extras/acpi.md:214:88

- Opencore-Vanilla-Desktop-Guide/troubleshooting/troubleshooting.md
✖ https://github.com/khronokernel/Opencore-Vanilla-Desktop-Guide/tree/d6ae62c258e16382e0746e9ffd1e9755c93b08d7/extras/extras/acpi.md:214:88

**Comment by khronokernel** [comment]
Ok so just pushed some fixes, ~~the only one I couldn't find was spoof.md~~ checking again and found it, got another one to push ;p

Regarding that bot, do you have a link? I'd be quite interested in running it every once and a while as I sometimes do mass commits where I don't even notice mistakes.

And again thank you for the help! I wouldn't have found a couple of those issues for sure
