### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by hereditarium** [khronokernel/Opencore-Vanilla-Desktop-Guide#29]
Hi, 
after applying NullCPU patch and AGPM injector i run Geekbenchmark 5. 
Results on OpenCL were around 8k, with nullcpupowermangement.kext my results were around 40k.

**Comment by khronokernel** [comment]
The issues tab is not a help forum, keep this kind of discussion on AMD OSX or other sites/forums. If there's an issue with the guide itself, I'm more than happy to correct it but this seems more like a hackintosh issue on your end
