### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by Matthew92007** [khronokernel/Opencore-Vanilla-Desktop-Guide#30]
The "Legacy Install" hyperlink is dead as of 1/28/2020 on
https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide/opencore-efi/mac-install

**Comment by khronokernel** [comment]
Thank you, fixed in latest commit: [e4d94f8](https://github.com/khronokernel/Opencore-Vanilla-Desktop-Guide/commit/e4d94f81c01858bcb53f60abe10dca6014b568b5)
