### ISSUE TITLE
ACPI Table Length/File Size mismatch

### ISSUE THREAD

**Issue by technicalflaw** [khronokernel/Opencore-Vanilla-Desktop-Guide#31]
Whilst transferring from Clover to OC I noticed that one of my custom SSDT tables wasn't being added. The reason is that OC verifies that the table length header (part of the aml file) is equal to the file size (which I assume Clover doesn't do). I fixed this by patching the table length and checksum in the aml file. 

Strictly speaking it's the fault of iASL when compiling the file, but might it be worth a note about it, either here or in the guide?

**Comment by khronokernel** [comment]
Sorry for the delay, forgot about this issue when I pushed the commit. I did add a note and thank you for this, friend actually had similar issue when he was converting to OpenCore so its not too uncommon to get this issue it seems
