### ISSUE TITLE
xcpm

### ISSUE THREAD

**Issue by technicalflaw** [khronokernel/Opencore-Vanilla-Desktop-Guide#32]
In the Clover Conversion guide, ```Kernel and Kext Patches => KernelXCPM``` is stated as being equivalent to ```Kernel -> Quirks -> AppleXcpmExtraMsrs -> YES```. It might be helpful to link to https://github.com/acidanthera/bugtracker/issues/365 which references additional ```_xcpm_bootstrap``` patches which may be needed.

It's probably not practical to list the many possible XCPM patches, but they can be converted from ```rEFIt_UEFI/Platform/kernel_patcher.c``` in the Clover source (although, for Google's sake, here's the Ivy Bridge patch for Catalina, taken from the ```KernelIvyBridgeXCPM()``` method of the aforementioned file)

```
Base: _xcpm_bootstrap
Comment: _xcpm_bootstrap (Ivy Bridge) 10.15
Count: 1
Enabled: YES
Find: 8D43C43C22
Identifier: kernel
Limit: 0
Mask: FFFF00FF
MinKernel: 19.
MaxKernel: 19.99.99
Replace: 8D43C63C22
ReplaceMask: 0000FF0000
Skip: 0
```

**Comment by khronokernel** [comment]
Thank you for this! Its been added in the latest commit: [3cd95b0](https://github.com/khronokernel/Opencore-Vanilla-Desktop-Guide/commit/3cd95b0bee6873b205b5c40ec99d21bc806fef92)
