### ISSUE TITLE
Missing NullCPUPowerManagment.kext.zip in extra-files

### ISSUE THREAD

**Issue by gillesdubois** [khronokernel/Opencore-Vanilla-Desktop-Guide#34]
Hi,

I spotted a missing file on your guide :) 

On general troubleshot -> Kernel Panic AppleIntelCPUPowerManagement.
See the report below : 

```
troubleshooting/troubleshooting.md
  274:267-274:418  warning  Link to unknown file: `../extra-files/NullCPUPowerManagment.kext.zip`  missing-file  remark-validate-links
  288:267-288:418  warning  Link to unknown file: `../extra-files/NullCPUPowerManagment.kext.zip`  missing-file  remark-validate-links
```

Regards,
Gilles Dubois.

**Comment by khronokernel** [comment]
Oh thank you! Fixed in latest commit: [6a4c654
](https://github.com/khronokernel/Opencore-Vanilla-Desktop-Guide/commit/6a4c654474b5ac570b0d29efa6d80e6d0fc35a3e)
