### ISSUE TITLE
No Section for Known issue

### ISSUE THREAD

**Issue by aki263** [khronokernel/Opencore-Vanilla-Desktop-Guide#39]
Hi 

We should add a section for know issue like there is a issue with MSI cards. Catalina would not install, I just spent like 4 days due to MSI card not working with Catalina Installer. Once I removed card and replaced with Geforece 210, it installed like a charm and once it was installed I switched back to RX5600XT and now its working fine.

**Comment by khronokernel** [comment]
This is a bit of an odd one, this wouldn't be an OC issue more of a GPU issue so this would be a better fit for the [GPU Buyers Guide](https://khronokernel-3.gitbook.io/catalina-gpu-buyers-guide/) instead. This is the second time I've seen an issue with MSI's Navi cards so I'll keep this in mind. If I see it some more, I'll consider adding it to the guide but atm this seems more of a fluke
