### ISSUE TITLE
Graphics section of clover-conversion/Clover-config.md

### ISSUE THREAD

**Issue by whatnameisit** [khronokernel/Opencore-Vanilla-Desktop-Guide#41]
https://github.com/khronokernel/Opencore-Vanilla-Desktop-Guide/blob/master/clover-conversion/Clover-config.md#graphics
I need to use InjectNvidia in OpenCore and I am not sure what value to give in DeviceID and Family. Are the names of these properties even correct?

**Comment by khronokernel** [comment]
Yes those are correct, you can check the Clover source. You'd enter the Vendor and deviceID of the card, they're in Data type if you're curious

**Comment by whatnameisit** [comment]
Can you be more specific on where to check please?
