### ISSUE TITLE
CFG Lock mentions incorrect kernel quirks

### ISSUE THREAD

**Issue by mlilley** [khronokernel/Opencore-Vanilla-Desktop-Guide#42]
At the end of each platform guide, under "Intel BIOS Settings", where you mention disabling the CFGLock setting, the guide says:

> enable both AppleCpuPmCfgLock and AppleCpuPmCfgLock under Kernel -> Quirks

I suspect this is a typo and should instead say:

> enable both AppleCpuPmCfgLock and **_AppleXcpmCfgLock_** under Kernel -> Quirks

This same typo appears many times.  Here's a link that should help locate all of them:
https://github.com/khronokernel/Opencore-Vanilla-Desktop-Guide/search?q=AppleCpuPmCfgLock&unscoped_q=AppleCpuPmCfgLock

Thanks for the awesome work, and cheers!

**Comment by khronokernel** [comment]
Well I actually just snuck a commit in: [a2640be](https://github.com/khronokernel/Opencore-Vanilla-Desktop-Guide/commit/a2640be466bfd2727f72c8ad18dd573261d9abd4)

Thanks again for the help, very much appreciated!
