### ISSUE TITLE
Plugin type guide process doesn't recommend altering device path.

### ISSUE THREAD

**Issue by mlilley** [khronokernel/Opencore-Vanilla-Desktop-Guide#43]
I suspect there may be a subtle issue with the 'Plugin type' guide:
https://khronokernel.github.io/Getting-Started-With-ACPI/Universal/plug.html

The guide reads:
> As we can see, the first processor in our list is PR00. This is what we'll be applying the plugin-type=1 property too. Now grab SSDT-PLUG and replace the default CPU0 with our PR00. Note that there are 2 mentions of CPU0 in the SSDT.

Whereas I suspect it really should also include language to make it clear one needs to take care to update the device path as well.  Note that the provided SSDT-PLUG.dsl has the device path as "_PR":
```
DefinitionBlock ("", "SSDT", 2, "ACDT", "CpuPlug", 0x00003000)
{
    External (_PR_.CPU0, ProcessorObj)
    Scope (\_PR.CPU0)
    ...
```

Like the example in the guide, my machine's DSDT also has the processor at _SB.PR00:
```
    Scope (_SB)
    {
        Processor (PR00, 0x01, 0x00001810, 0x06){}
        ...
```

If I followed the guide as written, I would end up with a SSDT containing "_PR.PR00" and not "_SB.PR00".  SSDTTime seems to agree - if I use it to automatically generate SSDT-PLUG for me, it outputs "_SB.PR00".

Thanks!

**Comment by khronokernel** [comment]
So a bit below I have the HEDT section that refers to the full path though rereading it now I see how it isn't very clear on all the parts that can have variation. I just pushed a commit in the [ACPI repo](https://github.com/khronokernel/Getting-Started-With-ACPI)

Also thanks for the issues, I saw the other ones but may be a little bit till I get to them
