### ISSUE TITLE
KALSR guide example math is incorrect

### ISSUE THREAD

**Issue by mlilley** [khronokernel/Opencore-Vanilla-Desktop-Guide#44]
The guide here:
https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide/extras/kalsr-fix#finding-the-slide-value

reads:
> So for example 0x35A converted to decimal becomes 858 and then +1 will give you slide=858.

Did you mean?
> So for example 0x35A converted to decimal becomes 858 and then +1 will give you **_slide=859_**.

**Comment by khronokernel** [comment]
Well I actually just snuck a commit in: [a2640be](https://github.com/khronokernel/Opencore-Vanilla-Desktop-Guide/commit/a2640be466bfd2727f72c8ad18dd573261d9abd4)

Thanks again for the help, very much appreciated!
