### ISSUE TITLE
(Catalina Stuck on) memory panic stackshot succeeded ** bytes traced 234 **

### ISSUE THREAD

**Issue by imranshad** [khronokernel/Opencore-Vanilla-Desktop-Guide#53]
Please help I'm stuck with error   " memory panic stackshot succeeded ** bytes traced 234 ** "

Using 
AMD A10, 7800, 
Nvidia Gforce 310 512MB, 
8GB Samsung Ram 1600MHZ,

Tried with clover as well but same error

**Comment by khronokernel** [comment]
This is not a help section, please keep this for issues with the guide itself. This kind of discussion is much more suitable on forums and such
