### ISSUE TITLE
windows .dsl to .aml problem

### ISSUE THREAD

**Issue by hgabe** [khronokernel/Opencore-Vanilla-Desktop-Guide#54]
How do I compile .dsl to .aml on windows and are the AcpiSamples meant to be compiled

**Comment by khronokernel** [comment]
There's an entire guide linked about this in the OC guide, you're told to read it...
[Getting started with ACPI](https://khronokernel.github.io/Getting-Started-With-ACPI/)

**Comment by hgabe** [comment]
lol my bad please close this
