### ISSUE TITLE
Need guide on switching from Clover to Opencore

### ISSUE THREAD

**Issue by iosoft** [khronokernel/Opencore-Vanilla-Desktop-Guide#6]
Dear Devs,

Your article is very very nice.
I would like to suggest you to also include a guide on **how to switch from Clover to Opencore**, specially when we already have a running Hackintosh with working System IDs and iCloud things.

Thanks.

**Comment by khronokernel** [comment]
@iosoft 
Hello, regarding you issue with OpenCore conversion the main things to keep in mind are keep original serial numbers and verify your En0 is still the same. Besides that there shouldn't be much on an issue as macOS won't notice much of a difference. Overall I'd like users to follow the the guide as a fresh slate as most users have many unneeded patches that can be harmful.

But I have a small section for converting Clover properties to OpenCore here:
https://github.com/khronokernel/Opencore-Vanilla-Desktop-Guide/blob/master/Clover2OC.md

Was there something more specific you were referring to or wished to suggest?

**Comment by paulkae** [comment]
hi!
running the latest Clover, but reading through the documentation I suppose I should switch to OC soon. However the link posted above is not working any more and search didn't help neither...

Is there any guide for switching? Or did I get sth wrong in the first place? Thank you very much!
