### ISSUE TITLE
Clover-config.md  possible mistake?

### ISSUE THREAD

**Issue by dreamwhite** [khronokernel/Opencore-Vanilla-Desktop-Guide#69]
> FixADP1:

> Renames device AC0_ to ADP1, see Rename-SSDT for an example

As far as I know, it doesn't only renames AC0_ to ADP1 but it also add the following AML code inside ADP1 (the old AC0_):

`Name (_PRW, Package (0x02) { 0x18, 0x03})`

Which effectively enables the peripheral

**Comment by khronokernel** [comment]
Oh thank you! Ironically I found it in my search for PCIRootUID: [Source](https://github.com/CloverHackyColor/CloverBootloader/blob/81f2b91b1552a4387abaa2c48a210c63d5b6233c/rEFIt_UEFI/Platform/FixBiosDsdt.cpp#L1677-L1692)

Fixed in latest commit: 3b3a368

**Comment by dreamwhite** [comment]
Some news about Clover patches: I've found that `ADP1` patches only the device called `AC0`. It seems that in some cases the device is called `AC`. The only way to find the correct device to patch is to look for `ACPI0003` inside DSDT. Below a screenshot that may be more clear:

![image](https://user-images.githubusercontent.com/17933708/79687598-bbe7ac80-8248-11ea-838f-15eaee5ab5cf.png)

May be it can be helpful for someone to add the following patches:

- Rename the device AC to ADP1

`into device label AC set_label begin ADP1 end;`

- Add the _PWR package to ADP1

`into device label ADP1 insert begin
Name (_PRW, Package (0x02)  // _PRW: Power Resources for Wake\n
{\n
0x18, \n
0x03\n
})\n
end;`

- Rename AC references with ADP1

`into_all all code_regex Notify\s\(AC,\s replace_matched begin Notify (ADP1\, end;`

`into_all all code_regex Notify\s\(\\_SB.AC,\s replace_matched begin Notify (\\_SB.ADP1\, end;`

Hope to be helpful for someone :D

Credits for the knowledge:

Rehabman and [system_adp1.txt](https://github.com/RehabMan/Laptop-DSDT-Patch/blob/master/system/system_ADP1.txt)
