### ISSUE TITLE
[AMD FX] Cannot boot into the installation

### ISSUE THREAD

**Issue by pexcn** [khronokernel/Opencore-Vanilla-Desktop-Guide#71]
Hello guys:
I was follow this guide try install macOS Catalina (10.15.3) on AMD FX series platform, but cannot boot into the installation, stuck on:
```
imageboot_setup_new: successfully authenticated /Install macOS Catalina.app/Contents/SharedSupport/BaseSystem.img
IOHDIXController: NOTE: administrator is creating non-ejectable disk image
```

More details on the topic I posted here a few days ago: https://github.com/AMD-OSX/AMD_Vanilla/issues/100. Hoping for help.

Thanks.

**Comment by khronokernel** [comment]
Hello,

Please keep the issues tab for issues relating to the guide itself, ***not*** for macOS installation issues unless there's an explicit error in the guide causing this.

Just to not leave you stranded, here's some tips:
* Try different USB ports, preferably USB 3.1/AsMedia ports as the chipset ports on 15/16h are borked in macOS
* Ask on forums or the [official AMD OSX Discord](https://discord.gg/qudxDed)

Your error seems USB related so look for those in your troubleshooting journey. 

Best of luck,

- Mykola

**Comment by pexcn** [comment]
Thank you for the information :)
