### ISSUE TITLE
Troubleshooting: Keyboard/Trackpad

### ISSUE THREAD

**Issue by jermafenser** [khronokernel/Opencore-Vanilla-Desktop-Guide#76]
I'm in the process of setting up a hackintosh laptop using opencore, and I ran into issues with the keyboard and trackpad not working during installation after following the guide.  

I finally figured out that I needed to include https://github.com/acidanthera/VoodooPS2 and it's dependency https://github.com/acidanthera/VoodooInput in my configuration to get the keyboard and trackpad to work.  

I think it would be useful for others to include something in the troubleshooting section about this behavior.

**Comment by dhinakg** [comment]
This is a desktop guide...

**Comment by jermafenser** [comment]
While I agree that the name of the guide includes 'Desktop' there are many considerations for laptops already throughout the guide.  Additionally, the ACPI subsection has explicit sections for laptops in it (I do realize it has been moved to a separate repository now).

I have not found any opencore laptop guides.  Does one exist?  Maybe a better solution is to include a link to an existing preferred guide instead if you do not want to further pollute this guide with laptop-specific content?

**Comment by dhinakg** [comment]
https://1revenger1.gitbook.io/laptop-guide is one we recommend. It references this guide for config.plist setup, but there is much more to a guide than just that.

**Comment by jermafenser** [comment]
Thank you for the link. I had a chance to briefly review it and it looks like there is a lot of good stuff there.  I'll have to review further and use it to further refine my configuration.
