### ISSUE TITLE
Unable to read compiled dst

### ISSUE THREAD

**Issue by mrbung84** [khronokernel/Opencore-Vanilla-Desktop-Guide#79]
Hello firstly i apologise as this is my first post and rather a noob question.
I have problems reading the converted ssdt tables as the reader suggested in the guide can't open it due to a syntax error on 1 line.
When i convert ssdt tables following precisely the guide, i get error message saying something like 19 dependencies exist but it does output the dst file...
I appreciate all your work and understand if my question is rather basic.
Thanks, MrBung

**Comment by khronokernel** [comment]
@mrbung84 Are you able to send over both the original untouched DSDT and the decompiled file?

**Comment by mrbung84** [comment]
@khronokernel yes
i followed the guide precisely, so here is the output folder within the
ssdttimemaster folder
and in it is also the decompiled file as followed by your guide.

I also booted into linux but found that the dsdt folder contained many many
files....

**Comment by khronokernel** [comment]
You forgot to send the files

**Comment by mrbung84** [comment]
[tables.zip](https://github.com/khronokernel/Opencore-Vanilla-Desktop-Guide/files/4399595/tables.zip)
[Results.zip](https://github.com/khronokernel/Opencore-Vanilla-Desktop-Guide/files/4399596/Results.zip)
 oops my noobiness shows i replied through email lol.
here they are: results from the program as suggested in the guide, tables is the booted from linux pull.
-thanks, mrbung

**Comment by khronokernel** [comment]
> I have problems reading the converted ssdt tables as the reader suggested in the guide can't open it due to a syntax error on 1 line.

Hmm, so I'm unable to reproduce this error. What kind of text editor where you using to read the .dsl file?

The external reference issue can be fixed when decompiling all the ACPI tables at once:
```
iasl -e DSDT.aml SSDT-1.aml .... etc
```

Since we're not planning on recompiling the DSDT, we don't have an issue with the 19 reference error *but* the correct way is to decompile all of them. I'll add a note on the guide about not worrying with the reference errors and on decompiling all at once.

**Comment by mrbung84** [comment]
Thank you so much. Actually thinking about it i was using your tree program so i think it was the wrong one lol. I'll have a look at using microsoft visual studio ? Or any other free windows one? I was even halfway through making a virtual machine with mac just to get to use xcode....

**Comment by khronokernel** [comment]
Oh haha PropTree's actually just for Plists, any text editor will do for .dsl files. Even the built in text editor in windows is fine

**Comment by mrbung84** [comment]
Cool thanks will have a go next couple of days

**Comment by khronokernel** [comment]
Note added: 3bcb499
