### ISSUE TITLE
Guide should mention how to compile .dsl to .aml 

### ISSUE THREAD

**Issue by Phlogi** [khronokernel/Opencore-Vanilla-Desktop-Guide#82]
Please also provide up-to-date links to the needed tools.

**Comment by khronokernel** [comment]
> Guide should mention how to compile .dsl to .aml

It's already in the guide, and you're told how to do as well: [Decompiling and **Compiling** ACPI Tables](https://khronokernel.github.io/Getting-Started-With-ACPI/Manual/compile.html)
And at the end of each page, there's in bold a link to that page: "[**Now you're ready to compile the SSDT!**](https://khronokernel.github.io/Getting-Started-With-ACPI/Manual/compile.html)"

> Please also provide up-to-date links to the needed tools.

If you're referring to the iASL binary for macOS, the reason Rehabman's repo is chosen is that it's the same one that [SSDTTime uses](https://github.com/corpnewt/SSDTTime/blob/08b6d11f71c031f228ca2da283dfa99318dcdf7e/Scripts/dsdt.py#L12). Just to keep things consistent, users can go and look for newer versions themselves if they so desire

And if you're referring to some other tool, please explicitly say them. There are many tools are linked in the guide
