### ISSUE TITLE
SetupVirtualMap bug

### ISSUE THREAD

**Issue by josemmc95** [khronokernel/Opencore-Vanilla-Desktop-Guide#89]
With the 0.5.7 you recommend set SetupVirtualMap to False, but with that setting macOS won't boot.

I had to revert it back to True to boot my system.

I followed the Kaby Lake guide (i5-7400)

**Comment by khronokernel** [comment]
What motherboard? SetupVirtualMap shouldn’t be needed on modern firmwares, would have to be some weird OEM issue

**Comment by josemmc95** [comment]
H270N-WiFi...

I set it to true and It booted again... 

Maybe it'd depend on motherboard...

**Comment by khronokernel** [comment]
What brand of motherboard?

**Comment by josemmc95** [comment]
Gigabyte

**Comment by telepati** [comment]
No problem on ASUS TUF Z390 Gaming with CoffeLake 9900K.

**Comment by khronokernel** [comment]
Asus should be fine, least drunk of the bunch.Will likely add a note about Gigabyte for that quirk but if more show up then I'll set it as default enabled

**Comment by josemmc95** [comment]
Add a note saying if the system doesn’t boot enable this quirk or something similar. Maybe it’s only related with some specific motherboards

**Comment by khronokernel** [comment]
Got some others to test, is in-fact Gigabyte that's drunk. Just pushed a commit adding the note
