### ISSUE TITLE
How to debug with opencore output txt file

### ISSUE THREAD

**Issue by crazyi** [khronokernel/Opencore-Vanilla-Desktop-Guide#9]
I stucked on the "PCI configuration begin" with OC and follow your advices[https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide/troubleshooting/debug], but how can I read this output txt file as they were all in binary?
BTW, how can I translate the following clover patch to OC?
		<key>KextsToPatch</key>
		<array>
			<dict>
				<key>Comment</key>
				<string>change 15 port limit to 31 in XHCI kext (X99-series) 10.12, GA-X99P-SLI has possible 26 ports?</string>
				<key>Disabled</key>
				<false/>
				<key>Find</key>
				<data>
				g710////EA==
				</data>
				<key>InfoPlistPatch</key>
				<false/>
				<key>Name</key>
				<string>AppleUSBXHCIPCI</string>
				<key>Replace</key>
				<data>
				g710////IA==
				</data>
			</dict>
			<dict>
				<key>Comment</key>
				<string>5960XPatch 10.12 by mano</string>
				<key>Disabled</key>
				<false/>
				<key>Find</key>
				<data>
				SIH7AAAAQA==
				</data>
				<key>InfoPlistPatch</key>
				<false/>
				<key>Name</key>
				<string>IOPCIFamily</string>
				<key>Replace</key>
				<data>
				SIH7AAAAgA==
				</data>
			</dict>
</array>

**Comment by IOIIIO** [comment]
> I stucked on the "PCI configuration begin" with OC

Try adding either `npci=0x2000` or `npci=0x3000` to your boot arguments.

> but how can I read this output txt file as they were all in binary?

What?

> BTW, how can I translate the following clover patch to OC?

Do you need to?

> change 15 port limit to 31

OpenCore has a built in XHCI limit patch, which is mentioned in the guide.

> 5960XPatch 10.12 by mano
 XHCI kext (X99-series) 10.12

Why would you be installing Sierra in 2019?

**Comment by khronokernel** [comment]
Closing as well this is not related to the guide instead being an install issue, please keep the issue page for guide issues
