### ISSUE TITLE
Broadwell-E Gitbook Section

### ISSUE THREAD

**Issue by ekwipt** [khronokernel/Opencore-Vanilla-Desktop-Guide#92]
**Kernel - Quirks section**

"Settings relating to the kernel, for us we'll be enabling AppleCpuPmCfgLock, AppleXcpmCfgLock, DisableIOMapper, PanicNoKextDump, PowerTimeoutKernelPanic and XhciPortLimit. Everything else should be left as default"

**Need to add - AppleXcpmExtraMsrs**

**Comment by khronokernel** [comment]
Fixed but you're in the wrong repo: [Dortania/OpenCore-Desktop-Guide](https://github.com/dortania/OpenCore-Desktop-Guide/commit/c2f86aac99b9af899e0062e1afc8aad44502a0e0)
