### ISSUE TITLE
Need to enable CSM for multiple monitor connect to iGPU

### ISSUE THREAD

**Issue by qiandongyq** [khronokernel/Opencore-Vanilla-Desktop-Guide#93]
I want to connect both my monitor to the iGPU, with CSM disable, it only shows one monitor. If I enable CMS, the not able to boot(20 mins still on loading state, printing all debug info).

My monitors connect to 1 DP and 1 HDMI. When CSM disabled. They both show the boot screen(choose option to boot) until the apple logo shows up, the HDMI one turned off.

**Comment by khronokernel** [comment]
1. This repo is to be closed in less than a week, if you have legitimate issues with the guide use the appropriate repo: https://github.com/dortania/OpenCore-Desktop-Guide
2. Issues tab is not for troubleshooting
3. If there is an issue with the guide itself, I'm more than happy to correct it. I do not see a direct issue from this issue tab

So please, keep per hack issues to the forums and discord. This is not a place to troubleshoot, this may be better suited to WhateverGreen's bug tracker but even then I'd recommend forums first before sending to the devs
